name: quran_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  quran: ^1.3.3
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  hijri: ^3.0.0
  google_mobile_ads: ^6.0.0
  icons_launcher: ^2.1.3
  rename: ^3.1.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  cached_network_image: ^3.2.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/json/aya.json
    - assets/json/hadith.json

icons_launcher:
  image_path: 'assets/img/playstore.png'
  platforms:
    android: true
    enable: true
